[package]
name = "membership-service"
version = "0.1.0"
edition = "2024"

[dependencies]
node = { path = "../node" }
tracing-service = { path = "../tracing-service" }
tokio.workspace = true
tracing.workspace = true
tokio-util.workspace = true
snafu.workspace = true
planus = "1.3.0"
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls", "ring"] }

[build-dependencies]
aaron-build = { path = "../aaron-build" }

[dev-dependencies]
node = { path = "../node" }
tempfile = "3"
